version: '3.8'

services:
  db-my-sql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql

  elasticsearch:
    container_name: e-es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:sha256-fbe8adcf94f9f57b8c75ae4a29018bd1f7e936e1e9870d4f50b1917e90735027
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
  redis:
    image: redis:latest
    container_name: e-redis-container
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis-data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management  # Sử dụng phiên bản RabbitMQ với giao diện quản lý
    container_name: e-rabbitmq
    ports:
      - "${RABBITMQ_WEB_CONSOLE_PORT}:15672"  # Web Management Console
      - "${RABBITMQ_AMQP_PORT}:5672"  # AMQP protocol (RabbitMQ)
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

networks:
  es-net:
    driver: bridge
