# Generated by Django 4.1.13 on 2024-10-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
