# Generated by Django 4.1.13 on 2024-10-31 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversations", "0002_message_is_bot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_bot",
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("system", "System"), ("user", "User"), ("bot", "Bot")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
