# Generated by Django 4.1.13 on 2024-10-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_remove_message_is_bot_message_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="params",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
