# Generated by Django 5.1.3 on 2024-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0004_message_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
    ]
