# Generated by Django 5.1.1 on 2024-10-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvariant",
            name="hot_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
