# Generated by Django 4.1.13 on 2024-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="source_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="source_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
